export const seedRows = [
  // =========================
  // CONCESSIONS — DRINKS
  // =========================
  {
    id: "employee-water",
    name: "Employee Water",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 4,
    backstockMin: 4,
    backstockMax: 4,
    fridgeSpace: 16,
    stockUnderBar: true,
  },
  {
    id: "customer-water",
    name: "Customer Water",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 4,
    backstockMin: 4,
    backstockMax: 6,
    fridgeSpace: 24,
    stockUnderBar: true,
  },
  {
    id: "starbucks-coffee",
    name: "Starbucks Coffee",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 8,
    stockUnderBar: false,
    orderMultiple: 15,
  },
  {
    id: "starbucks-coffee-different",
    name: "Starbucks Coffee (Different)",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 8,
    stockUnderBar: false,
  },
  {
    id: "red-bull",
    name: "Red Bull",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 10,
    stockUnderBar: true,
  },
  {
    id: "sugar-free-red-bull",
    name: "Sugar-free Red Bull",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 10,
    stockUnderBar: true,
  },
  {
    id: "red-bull-different",
    name: "Red Bull (Different)",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 10,
    stockUnderBar: false,
  },
  {
    id: "celsius-core-variety",
    name: "Celsius Core Variety",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 18,
    stockUnderBar: true,
  },
  {
    id: "monster",
    name: "Monster",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 8,
    stockUnderBar: true,
  },
  {
    id: "white-monster",
    name: "White Monster",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 8,
    stockUnderBar: true,
  },
  {
    id: "coffee-monsters",
    name: "Coffee Monsters",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 8,
    stockUnderBar: false,
  },
  {
    id: "monster-different",
    name: "Monster (Different)",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 8,
    stockUnderBar: false,
  },
  {
    id: "arizona-green-tea",
    name: "Arizona Green Tea",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 35,
    stockUnderBar: true,
    orderMultiple: 24,
  },
  {
    id: "half-half-tea",
    name: "Half & Half Tea",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 17,
    stockUnderBar: true,
    orderMultiple: 24,
  },
  {
    id: "gatorade-variety",
    name: "Gatorade Variety Pack",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 10,
    stockUnderBar: true,
  },
  {
    id: "gatorade-frost-variety",
    name: "Gatorade Frost Variety Pack",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 17,
    stockUnderBar: false,
  },
  {
    id: "mountain-dew",
    name: "Mountain Dew",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 16,
    stockUnderBar: true,
    orderMultiple: 36,
  },
  {
    id: "mountain-dew-baja",
    name: "Mountain Dew Baja Blast",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 8,
    stockUnderBar: false,
  },
  {
    id: "sprite",
    name: "Sprite",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 15,
    stockUnderBar: true,
  },
  {
    id: "sprite-zero",
    name: "Sprite Zero",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 0,
    stockUnderBar: true,
  },
  {
    id: "sunkist-squirt",
    name: "Sunkist/Squirt",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 16,
    stockUnderBar: true,
    orderMultiple: 24,
  },
  {
    id: "coke",
    name: "Coke",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 2,
    backstockMin: 2,
    backstockMax: 2,
    fridgeSpace: 20,
    stockUnderBar: true,
    orderMultiple: 35,
  },
  {
    id: "diet-coke",
    name: "Diet Coke",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 2,
    backstockMin: 2,
    backstockMax: 2,
    fridgeSpace: 15,
    stockUnderBar: true,
  },
  {
    id: "coke-zero",
    name: "Coke Zero",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 2,
    backstockMin: 2,
    backstockMax: 2,
    fridgeSpace: 16,
    stockUnderBar: false,
    orderMultiple: 12,
  },
  {
    id: "pepsi",
    name: "Pepsi",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 16,
    stockUnderBar: true,
    orderMultiple: 35,
  },
  {
    id: "diet-pepsi",
    name: "Diet Pepsi",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 10,
    stockUnderBar: true,
    expiration: "30-35",
  },
  {
    id: "dr-pepper",
    name: "Dr. Pepper",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 16,
    stockUnderBar: true,
    orderMultiple: 36,
  },
  {
    id: "canada-dry",
    name: "Canada Dry",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 24,
    stockUnderBar: true,
    orderMultiple: 24,
  },
  {
    id: "yoo-hoo",
    name: "Yoo-hoo",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 16,
    stockUnderBar: false,
    orderMultiple: 24,
  },
  {
    id: "coffee-creamer",
    name: "Coffee Creamer",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 0,
    backstockMax: 1,
    stockUnderBar: true,
  },
  {
    id: "coffee-pods",
    name: "Coffee Pods",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 0,
    backstockMax: 1,
    stockUnderBar: true,
  },

  // =========================
  // CONCESSIONS — SNACKS
  // =========================

  {
    id: "hersheys-bar-cc",
    name: "Hershey’s Bar (C&C)",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "12 mo",
    updatedAt: Date.now(),
  },
  {
    id: "mms-peanut",
    name: "M&M’s / Peanut M&M’s",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "4 mo",
    updatedAt: Date.now(),
  },
  {
    id: "kit-kat",
    name: "Kit Kat",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "10 mo",
    updatedAt: Date.now(),
  },
  {
    id: "reeses",
    name: "Reese’s",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "4 mo",
    updatedAt: Date.now(),
  },
  {
    id: "twix",
    name: "Twix",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "6 mo",
    updatedAt: Date.now(),
  },
  {
    id: "butterfinger",
    name: "Butterfinger",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "2 mo",
    updatedAt: Date.now(),
  },
  {
    id: "starburst",
    name: "Starburst",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "9 mo",
    updatedAt: Date.now(),
  },
  {
    id: "snickers",
    name: "Snickers",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "4 mo",
    updatedAt: Date.now(),
  },
  {
    id: "skittles-variety",
    name: "Skittles Variety",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "4 mo",
    updatedAt: Date.now(),
  },
  {
    id: "cinnamon-rolls",
    name: "Cinnamon Rolls",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    fridgeSpace: 8,
    stockUnderBar: true,
    expiration: "2 weeks",
    updatedAt: Date.now(),
  },
  {
    id: "honey-buns",
    name: "Honey Buns",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    orderMultiple: 12,
    expiration: "2 mo",
    updatedAt: Date.now(),
  },
  {
    id: "chex-mix-variety",
    name: "Chex Mix Variety Pack",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "4 mo",
    updatedAt: Date.now(),
  },
  {
    id: "famous-amos",
    name: "Famous Amos",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    orderMultiple: 42,
    expiration: "6 mo",
    updatedAt: Date.now(),
  },
  {
    id: "rice-krispies",
    name: "Rice Krispies",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "6 mo",
    updatedAt: Date.now(),
  },
  {
    id: "pop-tarts",
    name: "Pop Tarts",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    orderMultiple: 48,
    expiration: "8 mo",
    updatedAt: Date.now(),
  },
  {
    id: "oreo",
    name: "Oreo",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    orderMultiple: 30,
    expiration: "6 mo",
    updatedAt: Date.now(),
  },
  {
    id: "nutter-butter",
    name: "Nutter Butter",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "4 mo",
    updatedAt: Date.now(),
  },
  {
    id: "beef-jerky",
    name: "Beef Jerky",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    orderMultiple: 9,
    expiration: "12 mo",
    updatedAt: Date.now(),
  },
  {
    id: "slim-jims",
    name: "Slim Jims",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    orderMultiple: 120,
    expiration: "2 mo",
    updatedAt: Date.now(),
  },
  {
    id: "beef-sticks",
    name: "Beef Sticks",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "12 mo",
    updatedAt: Date.now(),
  },
  {
    id: "fritos-lays-doritos",
    name: "Fritos/Lays/Doritos",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    updatedAt: Date.now(),
  },
  {
    id: "ms-vickies-chips",
    name: "Ms Vickies Chips",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    expiration: "1 mo",
    updatedAt: Date.now(),
  },
  {
    id: "sunchips",
    name: "Sunchips",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    updatedAt: Date.now(),
  },
  {
    id: "veggie-straws",
    name: "Veggie Straws",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    updatedAt: Date.now(),
  },
  {
    id: "mini-pretzels",
    name: "Mini-Pretzels",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    updatedAt: Date.now(),
  },
  {
    id: "ritz-bitz",
    name: "Ritz Bitz",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 2,
    backstockMin: 1,
    backstockMax: 2,
    stockUnderBar: true,
    orderMultiple: 60,
    updatedAt: Date.now(),
  },
  {
    id: "cheez-it",
    name: "Cheez-it",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    orderMultiple: 30,
    updatedAt: Date.now(),
  },
  {
    id: "goldfish",
    name: "Goldfish",
    category: "Concessions",
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
    updatedAt: Date.now(),
  },
  // =========================
  // WORK SUPPLIES
  // =========================
  {
    id: "white-stickers",
    name: "White Stickers (for gun)",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "green-stickers",
    name: "Green Stickers (for gun)",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "paid-stickers",
    name: "Paid Stickers",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "mini-labels",
    name: "Mini Labels (con. stickers)",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "large-sticky-notes",
    name: "Large Sticky Notes",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    orderMultiple: 24,
  },
  {
    id: "small-sticky-notes",
    name: "Small Sticky Notes",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    orderMultiple: 16,
  },
  {
    id: "ziploc-bags",
    name: "Ziploc Bags",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    orderMultiple: 580,
  },
  {
    id: "packing-tape",
    name: "Packing Tape",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    orderMultiple: 6,
  },
  {
    id: "scotch-tape",
    name: "Scotch Tape",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    orderMultiple: 6,
  },
  {
    id: "printer-paper-supplies",
    name: "Printer Paper",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "counterfeit-pens",
    name: "Counterfiet Pens",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "team-bags",
    name: "Team Bags",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "penny-sleeves",
    name: "Penny Sleeves",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    orderMultiple: 1000,
  },
  {
    id: "slab-bags",
    name: "Slab Bags",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "toploaders-supplies",
    name: "Toploaders",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "pens",
    name: "Pens",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "coffee-cups",
    name: "Coffee Cups",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "expo-markers",
    name: "Expo Markers",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "customer-bags",
    name: "Customer Bags",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "hang-tags",
    name: "Hang Tags",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },
  {
    id: "printer-ink",
    name: "Printer Ink",
    category: "Work Supplies",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
  },

  // =========================
  // CLEANING
  // =========================
  {
    id: "paper-towel-rolls",
    name: "Paper Towel Rolls",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 6,
    backstockMin: 6,
    backstockMax: 6,
    stockUnderBar: true,
  },
  {
    id: "tissues",
    name: "Tissues",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 2,
    backstockMin: 2,
    backstockMax: 2,
    stockUnderBar: true,
  },
  {
    id: "napkins",
    name: "Napkins",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
  },
  {
    id: "multi-fold-paper-towels",
    name: "Multi-Fold Paper Towels",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
  },
  {
    id: "toilet-paper",
    name: "Toilet Paper",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
  },
  {
    id: "toilet-cleaner",
    name: "Toilet Cleaner",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
  },
  {
    id: "hand-soap",
    name: "Hand Soap",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
  },
  {
    id: "black-trash-bags",
    name: "Black Trash Bags",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
  },
  {
    id: "small-white-trash-bags",
    name: "Small White Trash Bags",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "latex-gloves-m",
    name: "Latex Gloves (M)",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "latex-gloves-xl",
    name: "Latex Gloves (XL)",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "fabuloso",
    name: "Fabuloso",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "hand-sanitizer",
    name: "Hand Sanitizer",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "fly-trap-substance",
    name: "Fly Trap Substance",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "disinfecting-wipes",
    name: "Disinfecting Wipes",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
  },
  {
    id: "glass-cleaner",
    name: "Glass Cleaner",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "alcohol-wipes",
    name: "Alcohol Wipes",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "duster-covers",
    name: "Duster Covers",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "swiffer-covers",
    name: "Swiffer Covers",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: false,
  },
  {
    id: "febreeze",
    name: "Febreeze",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
  },
  {
    id: "wall-scent-refills",
    name: "Wall Scent Dispenser Refills",
    category: "Cleaning",
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    stockUnderBar: true,
  },
];
