export const seedRows = [
  {
    category: "Concessions",
    name: "Employee Water",
    fridgeSpace: 16,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 4,
    barMin: 1,
    backstockMin: 4,
    backstockMax: 4,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Customer Water",
    fridgeSpace: 24,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 4,
    barMin: 1,
    backstockMin: 4,
    backstockMax: 6,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Starbucks Coffee",
    fridgeSpace: 8,
    stockUnderBar: false,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 15,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Starbucks Coffee (Different)",
    fridgeSpace: 8,
    stockUnderBar: false,
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Red Bull",
    fridgeSpace: 10,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 2,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Sugar-free Red Bull",
    fridgeSpace: 10,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 2,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Red Bull (Different)",
    fridgeSpace: 10,
    stockUnderBar: false,
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Celsius Core Variety",
    fridgeSpace: 18,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 2,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Monster",
    fridgeSpace: 8,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 3,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "White Monster",
    fridgeSpace: 8,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Coffee Monsters",
    fridgeSpace: 8,
    stockUnderBar: false,
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Monster (Different)",
    fridgeSpace: 8,
    stockUnderBar: false,
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Arizona Green Tea",
    fridgeSpace: 35,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 2,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 24,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Half & Half Tea",
    fridgeSpace: 17,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 24,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Gatorade Variety Pack",
    fridgeSpace: 10,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Gatorade Frost Variety Pack",
    fridgeSpace: 17,
    stockUnderBar: false,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Mountain Dew",
    fridgeSpace: 16,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 36,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Mountain Dew Baja Blast",
    fridgeSpace: 8,
    stockUnderBar: false,
    barQty: 0,
    storageQty: 0,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Sprite",
    fridgeSpace: 15,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Sprite Zero",
    fridgeSpace: 0,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Sunkist/Squirt",
    fridgeSpace: 16,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 2,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 24,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Coke",
    fridgeSpace: 20,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 2,
    barMin: 1,
    backstockMin: 2,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 35,
    expiration: "",
    storageLocation: "115",
    notes:
      "NOTE: Sheet has Min=2, Max=1 (max < min). Consider swapping or fixing.",
  },
  {
    category: "Concessions",
    name: "Diet Coke",
    fridgeSpace: 15,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 2,
    barMin: 1,
    backstockMin: 2,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes:
      "NOTE: Sheet has Min=2, Max=1 (max < min). Consider swapping or fixing.",
  },
  {
    category: "Concessions",
    name: "Coke Zero",
    fridgeSpace: 16,
    stockUnderBar: false,
    barQty: 0,
    storageQty: 5,
    barMin: 1,
    backstockMin: 2,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 12,
    expiration: "",
    storageLocation: "115",
    notes:
      "NOTE: Sheet has Min=2, Max=1 (max < min). Consider swapping or fixing.",
  },
  {
    category: "Concessions",
    name: "Pepsi",
    fridgeSpace: 16,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 2,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 35,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Diet Pepsi",
    fridgeSpace: 10,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 2,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "Case Size in sheet is '30-35' (range). Set later.",
  },
  {
    category: "Concessions",
    name: "Dr. Pepper",
    fridgeSpace: 16,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 36,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Canada Dry",
    fridgeSpace: 24,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 24,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Yoo-hoo",
    fridgeSpace: 16,
    stockUnderBar: false,
    barQty: 0,
    storageQty: 1,
    barMin: 1,
    backstockMin: 1,
    backstockMax: 1,
    vendor: "",
    orderMultiple: 24,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Coffee Creamer",
    fridgeSpace: 0,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 0,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
  {
    category: "Concessions",
    name: "Coffee Pods",
    fridgeSpace: 0,
    stockUnderBar: true,
    barQty: 0,
    storageQty: 0,
    barMin: 0,
    backstockMin: 0,
    backstockMax: 1,
    vendor: "",
    orderMultiple: undefined,
    expiration: "",
    storageLocation: "115",
    notes: "",
  },
] as const;
